### ISSUE TITLE
Almost invisible parameters in suggestions hints (PyCharm)

### ISSUE THREAD

**Issue by Eroppo** [subtheme-pro/monokai-pro#12]
In Machine and Octagon schemes the suggestions' hints (method parameters, packages) colors are almost invisible, especially selected one - gray on gray. Shown on the screenshots of both schemes (hard to see "print" parameters).
![pycharm64_2021-02-02_14-26-48](https://user-images.githubusercontent.com/13285107/106594514-42b11000-6563-11eb-8cd8-57266799e4d9.jpg)
![pycharm64_2021-02-02_14-25-49](https://user-images.githubusercontent.com/13285107/106594516-4349a680-6563-11eb-86b5-ee8199f016ef.jpg)

**Comment by jontaydev** [comment]
Fixed, update is available now from JetBrains.
