### ISSUE TITLE
Colors don't match official theme

### ISSUE THREAD

**Issue by jontaydev** [subtheme-pro/monokai-pro#16]
In many places, the token colors differ from the official Sublime and VSCode themes. For example, Python keywords are shown as red but the official themes show as blue. This is because the color scheme was originally forked from Material, but more work is needed to match the official theme.

Instead of going through every possible field, one idea is to create a converter tool that transforms a VSCode json file into a JetBrains xml file. This could be pulled in as a template, so specific things we add could sit alongside these settings.

Repo is started here: https://github.com/subtheme-pro/retheme

**Comment by ekzGuille** [comment]
I've just uploaded to latest version (1.12) and I though the theme was bugged because of some words that were red changed to blue.

**Comment by jontaydev** [comment]
Did you see an issue introduced in 1.2.1 that needs to be fixed? Or just something unexpected? I'm happy to make minor tweaks for now if needed, until the converter tool is completed.

**Comment by ekzGuille** [comment]
@jontaydev I have only seen the light blue keywords what were supposed to be red so far. In my case was the `this.`, `return`, `if`, etc. words on Typescript.

![image](https://user-images.githubusercontent.com/15647197/116622812-91452f00-a945-11eb-8671-4038f0e4215a.png)

Left <1.2.1
Right 1.2.1

**Comment by jontaydev** [comment]
I would compare your source with VSCode or Sublime because I think the official default keywords should be blue.

**Comment by ekzGuille** [comment]
![image](https://user-images.githubusercontent.com/15647197/116652377-57941880-a985-11eb-9152-da22018922aa.png)
Same snippet code in Visual Studio Code shows a mixure of both blue and red.

Comparing with VSCode versión I've just noticed Template String (`${}`) curly braces are different.

Anyway it's a great work!

(It's Filter Machine effect btw)

**Comment by jontaydev** [comment]
I'm gonna hammer away at the converter script a bit more and if it turns out to be too difficult I'll look at some of these differences by hand.

**Comment by jlyon87** [comment]
Installed 1.2.1 tonight and the issue is particularly **jarring** in a Java project. 

Keywords such as 
import, public, private, protected, static, final, primitive types, return (and I'm sure I'm missing a lot more) should be that red/magenta color. 

<img width="730" alt="image" src="https://user-images.githubusercontent.com/9729366/116767768-e6da1400-a9f7-11eb-9e61-4b38ebeba57b.png">

**Comment by jontaydev** [comment]
Uploaded 1.2.2 which reverts the default keyword color back to red (which is what Material used). This is technically incorrect, but I will hold off further changes until the converter tool is complete and all languages can be tested more thoroughly in a separate branch.

https://plugins.jetbrains.com/plugin/13643-monokai-pro-theme/versions/stable/118780

**Comment by jlyon87** [comment]
Thanks @jontaydev 
Can you say when 1.2.2 should arrive in the jetbrains plugin repos?
https://plugins.jetbrains.com/plugin/13643-monokai-pro-theme/versions

**Comment by jontaydev** [comment]
@jlyon87 usually within two days

**Comment by 3jins** [comment]
It seems this issue is reproduced in 1.3.1.
I've rollbacked the plugin to 1.2.2. I'll wait for the fixed version.

**Comment by jontaydev** [comment]
Dang, sorry guys. The 1.3.2 patch is available now: https://plugins.jetbrains.com/plugin/13643-monokai-pro-theme/versions/stable/126334
