### ISSUE TITLE
Missing checkboxes on commit changes window

### ISSUE THREAD

**Issue by meendoo** [subtheme-pro/monokai-pro#17]
**Describe the bug**
After upgrading to release 1.2 I noticed that checkboxes are missing on Commit changes dialog

**To Reproduce**
Open Commit Changes dialog

**Screenshots**
![image](https://user-images.githubusercontent.com/3496704/116402271-7b901680-a82c-11eb-92b6-16e2f8a2e562.png)

**Application:**
IntelliJ Ultimate 2021.1

**Comment by chillstreem** [comment]
All checkboxes also missing in Pycharm's Settings Window after the latest update
[PyCharm 2021.1]
![Screenshot 2021-04-28 150415](https://user-images.githubusercontent.com/67348542/116408568-3de2bc00-a833-11eb-9bca-a2627d3a231c.jpg)

**Comment by meendoo** [comment]
1.2.1 release fixed the issue.
