### ISSUE TITLE
Feature needed: Custom accent color

### ISSUE THREAD

**Issue by ksundong** [subtheme-pro/monokai-pro#19]
This is a good project, I love it.

Can I customize custom accent color?

**Comment by jontaydev** [comment]
What features where you thinking of customizing, specifically? I don't have a ui panel that allows customizing any of the colors, currently. However, you can clone the repository and build the template with your own modifications (using the [yaml](https://github.com/subtheme-pro/monokai-pro/blob/master/sublate.yaml) and [template](https://github.com/subtheme-pro/monokai-pro/blob/master/apps/jetbrains/templates/theme.json)).

**Comment by ksundong** [comment]
I'm looking for Material UI Theme's custom accent color feature.
Thank you for your answer!
