### ISSUE TITLE
How to set file icons

### ISSUE THREAD

**Issue by Deja-vuuu** [subtheme-pro/monokai-pro#22]
it is my 
![image](https://user-images.githubusercontent.com/27748682/127424100-49ffb26f-8a95-4355-820a-75faeabb843d.png)

**Comment by jontaydev** [comment]
Unfortunately I cannot bundle the official Monokai Pro file icons with this theme. For the screenshots, I used [Atom Material Icons](https://plugins.jetbrains.com/plugin/10044-atom-material-icons), but there are others available if you search the plugin repo.
