### ISSUE TITLE
Visalization problem with callstack marked line

### ISSUE THREAD

**Issue by lujop** [subtheme-pro/monokai-pro#9]
While debugguing and going down the callstack you can't see correctly lines thar are part of callstack because the call stack selector indicator uses the same color than parentesis:

![idea64_TTGbqVYu5z](https://user-images.githubusercontent.com/920260/96852930-0b0dd480-145a-11eb-9484-32a7c538af39.png)

**Comment by jontaydev** [comment]
Sorry for the late response, can you give me a little more information about what you are looking at? Which tool are you using, and what panel are you looking at in the screenshot you posted?

Thanks.

**Comment by lujop** [comment]
IntelliJ and normal code window while debugging, execution is stopped in a breakpoint, and the gray line is one line that is part of the call stack to the line you are stopped

**Comment by jontaydev** [comment]
Updated the colors, changes are available now via JetBrains repository.
